project_id = "gmprigvmotrdrayxacnl"

[functions.fetch-youtube-stats]
verify_jwt = false

[functions.fetch-viewstats]
verify_jwt = true

[functions.refresh-social-stats]
verify_jwt = false

[functions.refresh-ig-media]
verify_jwt = false

[functions.upsert-analytics]
verify_jwt = false
